version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: my_postgres_mybatis
    restart: always
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: mydb
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - /D/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  postgres_data:
